### ISSUE TITLE
Stopped Receiving:    Received event with handler LAN client handler

### ISSUE THREAD

**Issue by baobab67** [toddaustin07/edge_envisalink#3]
Using with Envisalink 3 with 193 firmware. Seemed to be working and getting LAN client responses.

After upgrade of EnvisaLink firmware to 01.12.202 now seem to never received "  Received event with handler LAN client handler"
and status of the sensors etc are not updated.

After deleting the DSC Primary Device and reconnecting, it seemed to work again.

**Comment by toddaustin07** [comment]
Hello - Thanks for reporting the issue.  It seems the connection with the Envisalink could not be established after your firmware update.  It's difficult to tell what happened without some log output.  But I'm glad it's working for you again.  In the future if a similar problem arises, rather than deleting the device or reinstalling the driver, what I would suggest is to temporarily change the Envisalink LAN address in device Settings to something else, wait 10 seconds or so, then change it back to the correct address.  This will force a reset of the connection to Envisalink.
